DROP DATABASE IF EXISTS MOTWDECK;
CREATE DATABASE IF NOT EXISTS MOTWDECK CHARACTER SET utf8 COLLATE utf8_spanish_ci;
USE MOTWDECK;

CREATE TABLE PLAYBOOKS(
	ID INTEGER PRIMARY KEY,
    TITLE VARCHAR(25),
    LEGEND TEXT
);
INSERT INTO PLAYBOOKS VALUES
(1, "The Chosen", "Your birth was propheseid. You are the Chosen One, and with your abilities you can save the world. If you fail, all will be destroyed. It all rests on yoy. Only you."),
(2, "The Crooked", "Yeah, I´ve been around the block. A bit of this, a bit of that. When I came across the secret underworld of monsters and magic... well... it wasn´t so different from  the underworld I already knew. It was easy to find and angle, just like before."),
(3, "The Divine", "I am the Light, the Sword. I am sent to defend the meek from Darkness. All Evil fears me, for I am its end."),
(4, "The Expert", "I have dedicated my life to the study of the supernatural. I know their habits, their weaknesses. I may not be youngest or strongest, but my knowledge makes me the biggest threat."),
(5, "The Flake", "Everythinng´s connected. But not everyone can see the patterns, and most people don´t even look that hard. But me, I can never stop looking deper. I can never stop seeing the truth. I spot the patterns. That´s how I found the monsters, and that´s how I help kill them."),
(6, "The Initiate", "Since the dawn of history, we have been the bulwark against Darkness. We know the Evils of the world, and we stand against them so that the mass of humanity need not fear. We are the Flame that cleanses the Shadows."),
(7, "The Monstruous", "I feel the hunger, the lust of destroy. But I fight it: I never give in. I´m not human any more, not really, but I have to protect those who still are. That way I can tell myself I´m different to the other monsters. Sometimes I can even believe it."),
(8, "The Mundane", "You heard about how monsters only pick on people with crazy powers who can fight back on even terms? Yeah, me neither. But, hell, i ended up in this monster-hunting team so I gotta do what I can, right?"),
(9, "The Professional", "It´s kind of strange when your regular 9-to-5 job is to hunt down monsters. Still, that´s the job I took on when I joined this outfit. It pays well, and the benefits are good. Like they say \"You don´t have to be crazy to work here, but it sure helps!\""),
(10, "The Spell-Slinger", "Fight fire with fire magic."),
(11, "The Spooky", "I can do things, things thet normal people can´t. But there´s a price--I haven´t paid it full, yet, but the bill´s gonna come due soon. It´s best I don´t tell you any more. You get too close, you´ll get hurt."),
(12, "The Wronged", "They took my loved ones. Back then I wasn´t strong enought to fight, but I studied, trained, and now I´m ready to cleanse the world of their taint. I´ll kill them all, That´s all i have left.");
CREATE TABLE PLAYER(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(80) UNIQUE,
    NICK VARCHAR(30),
    PASSWORDHASH VARCHAR(255)
);
/*
	INSERTS
*/
CREATE TABLE MOVES(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    PLB_ID INTEGER,
    MOVE_TYPE VARCHAR(25),
    MOVE_NAME VARCHAR(25),
    MOVE_DESCRIPTION TEXT,
    CONSTRAINT FK_MO_PLB FOREIGN KEY (PLB_ID) REFERENCES PLAYBOOKS (ID)
		ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO MOVES VALUES 
#Chosen
(1,1,"MOVES","Destiny’s Plaything","At the beginning of each mystery, roll +Weird to see what is revealed about your immediate future. On a 10+, the Keeper will reveal a useful detail about the coming mystery. On a 7-9 you get a vague hint about it. On a miss, something bad is going to happen to you."), 
(2,1,"MOVES","I’m Here For A Reason","There’s something you are destined to do. Work out the details with the Keeper, based on your fate. You cannot die until it comes to pass. If you die in play, then you must spend a Luck point. You will then, somehow, recover or be returned to life. Once your task is done (or you use up all your Luck), all bets are of"), 
(3,1,"MOVES","The Big Entrance","When you make a showy entrance into a dangerous situation, roll +Cool. On 10+ everyone stops to watch and listen until you finish your opening speech. On a 7-9, you pick one person or monster to stop, watch and listen until you finish talking. On a miss, you’re marked as the biggest threat by all enemies who are present"), 
(4,1,"MOVES","Devastating","When you inflict harm, you may inflict +1 harm."), 
(5,1,"MOVES","Dutiful","When your fate rears its ugly head, and you act in accordance with any of your fate tags (either heroic or doom) then mark experience. If it’s a heroic tag, take +1 forward."), 
(6,1,"MOVES","Invincible","You always count as having 2-armour. This doesn’t stack with other protection"), 
(7,1,"MOVES","Resilience","You heal faster than normal people. Any time your harm gets healed, heal an extra point. Additionally, your wounds count as 1-harm less for the purpose of the Keeper’s harm moves"), 
(8,1,"MOVES","Nightmares and visions",""), 
(9,1,"FATE","Some weirdo told you",""), 
(10,1,"FATE","An ancient cult found you",""), 
(11,1,"FATE","Sought out by your nemesis",""), 
(12,1,"FATE","Attacked by monsters",""), 
(13,1,"FATE","Trained from birth",""), 
(14,1,"FATE","You found the prophecy",""), 
(15,1,"HEROIC","Sacrifice",""), 
(16,1,"HEROIC","You are the Champion",""), 
(17,1,"HEROIC","Visions",""), 
(18,1,"HEROIC","Secret training",""), 
(19,1,"HEROIC","Magical powers",""), 
(20,1,"HEROIC","Mystical inheritance",""), 
(21,1,"HEROIC","A normal life",""), 
(22,1,"HEROIC","True love",""), 
(23,1,"HEROIC","You can save the world",""), 
(24,1,"HEROIC","Hidden allies",""), 
(25,1,"HEROIC","The end of monsters",""), 
(26,1,"HEROIC","Divine help",""), 
(27,1,"DOOM","Death",""), 
(28,1,"DOOM","You can’t save everyone",""), 
(29,1,"DOOM","Impossible love",""), 
(30,1,"DOOM","Failure",""), 
(31,1,"DOOM","A nemesis",""), 
(32,1,"DOOM","No normal life",""), 
(33,1,"DOOM","Loss of loved ones",""), 
(34,1,"DOOM","Treachery",""), 
(35,1,"DOOM","Doubt",""), 
(36,1,"DOOM","Sympathy with the enemy",""), 
(37,1,"DOOM","Damnation",""), 
(38,1,"DOOM","Hosts of monsters",""), 
(39,1,"DOOM","The end of days",""), 
(40,1,"DOOM","The source of Evil",""),
#Crooked
(41,2,"BACKGROUND","Hoodlum","You can use Tough instead of Charm to manipulate someone with threats of violence"), 
(42,2,"BACKGROUND","Burglar","When you break into a secure location, roll +Sharp. On a 10+ pick three, on a 7-9 pick two: you get in undetected, you get out undetected, you don’t leave a mess, you find what you were after."), 
(43,2,"BACKGROUND","Grifter","When you are about to manipulate someone, you can ask the Keeper “What will convince this person to do what I want?” The Keeper must answer honestly, but not necessarily completely"), 
(44,2,"BACKGROUND","Fixer","If you need to buy something, sell something, or hire someone, roll +Charm. On a 10+ you know just the person who will be interested. On a 7-9 you know the only person who can do it, but there’s a complication. Pick one: you owe them; they screwed you over; you screwed them over. On a miss, the only person who can help is someone who absolutely hates you."), 
(45,2,"BACKGROUND","Assassin","When you take your first shot at an unsuspecting target, do +2 Harm"), 
(46,2,"BACKGROUND","Charlatan","When you want people to think you are using magic, roll +Cool. On a 10 or more, your audience is amazed and fooled by your illusion. On a 7-9 you tripped up a couple of times, maybe someone will notice. You may also manipulate people with fortune telling. When you do that, ask “What are they hoping for right now?” as a free question (even on a miss)."), 
(47,2,"BACKGROUND","Pickpocket","When you steal something small, roll +Charm. On a 10 or more, you get it and they didn’t notice you taking it. On a 7-9 either you don’t grab it, you grab the wrong thing, or they remember you later: your choice."), 
(48,2,"MOVES","Artifact","You ‘found’ a magical artifact with handy powers, and kept it. Pick one: Protective amulet (1-armour magic recharge), Lucky charm (may be used as a Luck point, once only), Grimoire (studying the book gives +1 forward to use magic), Skeleton key (opens any magically sealed lock), Imp stone (A weak demon is bound to serve the holder. The imp must be summoned with the use magic move)."), 
(49,2,"MOVES","Crew","You have a regular crew, a team of three or four people who will help you out with pretty much anything. They count as a team (see page 119)."), 
(50,2,"MOVES","Deal with the Devil","You sold your soul to the Devil. Pick one or two things you got out of the deal: wealth, fame, youth, sensual gratification, skill (add +1 to two ratings). Payment is due either when you die, in six months (if you picked two things) or otherwise in a year."), 
(51,2,"MOVES","Friends on the Force","You know a few cops who can be persuaded to look the other way, or do you a favour, for certain considerations. You can act under pressure to get in touch with them when you need to divert any law enforcement attention. There will be a cost, although maybe not right now"), 
(52,2,"MOVES","Made","You’re “made” in a gang. Name the gang and describe how their operations tie into your background. You can call on gang members to help you out, but they’ll expect to be paid. Your bosses will have requests for you now and again, but you’ll be paid. Minor trouble will be overlooked, but you better not screw over any other made gangsters"), 
(53,2,"MOVES","Driver","You have +1 ongoing while driving, plus you can hotwire anything (the older it is, the fewer tools you need to do it). You also own two handy, widely-available vehicles (perhaps a sportscar and a van)."), 
(54,2,"MOVES","Home Ground","Your crew made a point of keeping the locals happy - keeping them safe, ensuring things always went down okay. When you’re back in your old neighbourhood, you can always find people who will hide you or help you with a minor favour, no questions asked."), 
(55,2,"MOVES","Notorious","You have a reputation from your criminal past. When you reveal who you are, your terrifying reputation counts as a reason for people to do what you ask, for the manipulate someone move. Revealing your identity to someone can create other problems later, of course."), 
(56,2,"HEAT","A police detective, , has made it a personal goal to put you away",""), 
(57,2,"HEAT","You have a rival from your background, , who never misses a chance to screw you over.",""), 
(58,2,"HEAT","You pissed off a well-connected criminal, , and they’ll do whatever they can to destroy you",""), 
(59,2,"HEAT","is someone with special powers, a person or monster, who you took advantage of",""), 
(60,2,"HEAT","is an old partner you betrayed in the middle of a job.",""), 
(61,2,"UNDERWORLD","The target of a job was a dangerous creature. Pick one: vampire, werewolf, troll, reptiloid.",""), 
(62,2,"UNDERWORLD","You worked with someone who was more than they seemed. Pick one: sorcerer, demon, faerie, psychic.",""), 
(63,2,"UNDERWORLD","You were hired by something weird. Pick one: immortal, god, outsider, witch.",""), 
(64,2,"UNDERWORLD","Things went south on a job—including, but not limited to, running into (choose one): a horde of goblins, a hunger of ghouls, a dream-eater, a salamander",""),
#Divine
(65,3,"MOVES","Boss from Beyond","At the beginning of each mystery, roll +Weird. On a 10+, your Superiors ask you to do something simple. On a 7-9, they ask you to do something complicated or difficult. In either case, you get to ask them one of the questions from the investigate a mystery move right now. On a miss, you are required to do something terrible. If you do not accomplish what they’ve ordered, you cannot use this move again until you have made up for your failure"), 
(66,3,"MOVES","Angel Wings","You can go instantly to anywhere you’ve visited before, or to a person you know well. When you carry one or two people with you, roll +Weird. On a 10+ you all go where you wanted. On a 7-9, you don’t quite manage it. Either you are all separated, or you all appear in the wrong place"), 
(67,3,"MOVES","What I Need, When I Need It","You may store any small object you own, putting it into a magical space nobody can get to. You may retrieve anything you stored at any time; it appears in your hand"), 
(68,3,"MOVES","Smite","Your body and divine weapon always count as a weakness against the monsters you fight. Your unarmed attacks are 2-harm intimate hand messy"), 
(69,3,"MOVES","Soothe","When you talk to someone for a few seconds in a quiet voice, you can calm them down, blocking any panic, anger, or other negative emotions they have. This works even if the thing that freaked them out is still present, as long as your voice can be heard."), 
(70,3,"MOVES","Lay On Hands","Your touch can heal injury and disease. When you lay your hands on someone hurt, roll +Cool. On a 10+, heal 2 harm or an illness, plus they’re stabilized. On a 7-9, you can heal the harm or illness as on a 10+, but you take it into yourself. On a miss, your aura causes them extra harm."), 
(71,3,"MOVES","Cast Out Evil","You may banish an unnatural creature from your presence. Roll +Tough. On a 10+ it is banished. On a 7-9 it takes a little while for the banishing to take effect—the creature has time to make one or two actions. Either way, the banished creature is unharmed, and you have no control over where it goes. This move may be used on unnatural hunters (e.g. the Monstrous). On a miss, something is keeping it here. That’s bad."), 
(72,3,"MISSION","You are here to fight the schemes of an Adversary.",""), 
(73,3,"MISSION","The End of Days approaches. Your role is to guide these hunters and prevent it from coming to pass.",""), 
(74,3,"MISSION","The End of Days approaches. Your role is to guide these hunters and ensure it comes to pass.",""), 
(75,3,"MISSION","You have been exiled. You must work for the cause of Good without drawing attention from your brothers and sisters, as they are bound to execute you for your crimes",""), 
(76,3,"MISSION","One of the other hunters has a crucial role to play in events to come. You must prepare them for their role, and protect them at any cost.",""), 
#Expert
(77,4,"MOVES","I’ve Read About This Sort Of Thing","Roll +Sharp instead of +Cool when you act under pressure"), 
(78,4,"MOVES","Often Right","When a hunter comes to you for advice about a problem, give them your honest opinion and advice. If they take your advice, they get +1 ongoing while following your advice, and you mark experience"), 
(79,4,"MOVES","Preparedness","When you need something unusual or rare, roll +Sharp. On a 10+, you have it here right now. On a 7-9 you have it, but not here: it will take some time to get it. On a miss, you know where it is, but it’s somewhere real bad"), 
(80,4,"MOVES","It Wasn’t As Bad As It Looked","Once per mystery, you may attempt to keep going despite your injuries. Roll +Cool. On a 10+, heal 2 harm and stabilize your wounds. On a 7-9 you may either stabilize or heal 1 harm. On a miss, it was worse than it looked: the Keeper may inflict a harm move on you, or make your wounds unstable"), 
(81,4,"MOVES","Precise Strike","When you inflict harm on a monster, you can aim for a weak spot. Roll +Tough. On a 10+ you inflict +2 harm. On a 7-9 you inflict +1 harm. On a miss, you leave yourself open to the monster"), 
(82,4,"MOVES","The Woman (or Man) With The Plan","At the beginning of each mystery, roll +Sharp. On a 10+ hold 2, on a 7-9 hold 1. Spend the hold to be where you need to be, prepared and ready. On a miss, the Keeper holds 1 they can spend to put you in the worst place, unprepared and unready"), 
(83,4,"MOVES","Dark Past","If you trawl through your memories for something relevant to the case at hand, roll +Weird. On a 10+ ask the Keeper two questions from the list below. On a 7-9 ask one. On a miss, you can ask a question anyway but that will mean you were personally complicit in creating the situation you are now dealing with. The questions are: • When I dealt with this creature (or one of its kind), what did I learn? • What black magic do I know that could help here? • Do I know anyone who might be behind this? • Who do I know who can help us right now?"), 
(84,4,"HAVEN","Lore Library","When you hit the books, take +1 forward to investigate the mystery (as long as historical or reference works are appropriate)"), 
(85,4,"HAVEN","Mystical Library","If you use your library’s occult tomes and grimoires, preparing with your tomes and grimoires, take +1 forward for use magic."), 
(86,4,"HAVEN","Protection Spells","Your haven is safe from monsters—they cannot enter. Monsters might be able to do something special to evade the wards, but not easily"), 
(87,4,"HAVEN","Armory","You have a stockpile of mystical and rare monster-killing weapons and items. If you need a special weapon, roll +Weird. On a 10+ you have it (and plenty if that matters). On a 7-9 you have it, but only the minimum. On a miss, you’ve got the wrong thing"), 
(88,4,"HAVEN","Infirmary","You can heal people, and have the space for one or two to recuperate. The Keeper will tell you how long any patient’s recovery is likely to take, and if you need extra supplies or help"), 
(89,4,"HAVEN","Workshop","You have a space for building and repairing guns, cars and other gadgets. Work out with the Keeper how long any repair or construction will take, and if you need extra supplies or help"), 
(90,4,"HAVEN","Oubliette","This room is isolated from every kind of monster, spirit and magic that you know about. Anything you stash in there can’t be found, can’t do any magic, and can’t get out"), 
(91,4,"HAVEN","Panic Room","This has essential supplies and is protected by normal and mystical means. You can hide out there for a few days, safe from pretty much anything"), 
(92,4,"HAVEN","Magical Laboratory","You have a mystical lab with all kinds of weird ingredients and tools useful for casting spells (like the use magic move, big magic, and any other magical moves)"), 
#Flake
93,5,"MOVES","Connect the Dots","At the beginning of each mystery, if you look for the wider patterns that current events might be part of, roll +Sharp. On a 10+ hold 3, and on a 7-9 hold 1. Spend your hold during the mystery to ask the Keeper any one of the following questions: • Is this person connected to current events more than they are saying? • When and where will the next critical event occur? • What does the monster want from this person? • Is this connected to previous mysteries we have investigated? • How does"), 
(94,5,"MOVES","Crazy Eyes","You get +1 Weird (max +3)."), 
(95,5,"MOVES","See, It All Fits Together","You can use Sharp instead of Charm when you manipulate someone"), 
(96,5,"MOVES","Suspicious Mind","If someone lies to you, you know it."), 
(97,5,"MOVES","Often Overlooked","When you act all crazy to avoid something, roll +Weird. On a 10+ you’re regarded as unthreatening and unimportant. On a 7-9, pick one: unthreatening or unimportant. On a miss, you draw lots (but not all) of the attention"), 
(98,5,"MOVES","Contrary","When you seek out and receive someone’s honest advice on the best course of action for you and then do something else instead, mark experience. If you do exactly the opposite of their advice, you also take +1 ongoing on any moves you make pursuing that course"), 
(99,5,"MOVES","Net Friends","You know a lot of people on the Internet. When you contact a net friend to help you with a mystery, roll +Charm. On a 10+, they’re available and helpful—they can fix something, break a code, hack a computer, or get you some special information. On a 7-9, they’re prepared to help, but it’s either going to take some time or you’re going to have to do part of it yourself. On a miss, you burn some bridges"), 
(100,5,"MOVES","Sneaky","When you attack from ambush, or from behind, inflict +2 harm"), 
#Initiate
(101,6,"MOVES","When you are in good standing with your Sect, at the beginning of each mystery, roll +Charm. On a 10+ they provide some useful info or help in the field. On a 7-9 you get a mission associated with the mystery, and if you do it you’ll get some info or help too. On a miss, they ask you to do something bad. If you fail a mission or refuse an order, you’ll be in trouble with the Sect until you atone",""), 
(102,6,"MOVES","Ancient Fighting Arts","When using an old-fashioned hand weapon, you inflict +1 harm and get +1 whenever you roll protect someone."), 
(103,6,"MOVES","Mystic","Every time you successfully use magic, take +1 forward."), 
(104,6,"MOVES","Fortunes","The Sect has ancient prophecies or divination techniques to predict the future. Once per mystery, you may use them. If you look at what the future holds, roll +Weird. On a 10+ hold 3, and on a 7-9 hold 1. On a miss, you get bad information and the Keeper decides how that affects you. Spend your hold to: • have a useful object ready. • be somewhere you are needed, just in time. • take +1 forward, or give +1 forward to another hunter. • retroactively warn someone about an attack, so that it doesn’t happen"), 
(105,6,"MOVES","Sacred Oath","You may bind yourself to a single goal, forsaking something during your quest (e.g. speech, all sustenance but bread and water, alcohol, lying, sex, etc). Get the Keeper’s agreement on this—it should match the goal in importance and difficulty. While you keep your oath and work towards your goal, mark experience at the end of every session and get +1 on any rolls that directly help achieve the goal. If you break the oath, take -1 ongoing until you have atoned"), 
(106,6,"MOVES","Mentor","You have a mentor in the Sect: name them. When you contact your mentor for info, roll +Sharp. On a 10+, you get an answer to your question, no problem. On a 7-9 you choose: they’re either busy and can’t help, or they answer the question but you owe a favour. On a miss, your question causes trouble."), 
(107,6,"MOVES","Apprentice","You have an apprentice: name them. Your job is to teach them the Sect’s ways. They count as an ally: subordinate (motivation: to follow your instructions to the letter)"), 
(108,6,"MOVES","Helping Hand","When you successfully help out another hunter, they get +2 instead of the usual +1"), 
(109,6,"MOVES","That Old Black Magic","When you use magic, you can ask a question from the investigate a mystery move as your effect"), 
(110,6,"GOOD TRADITIONS","Knowledgable",""), 
(111,6,"GOOD TRADITIONS","Ancient lore",""), 
(112,6,"GOOD TRADITIONS","Magical lore",""), 
(113,6,"GOOD TRADITIONS","Fighting arts",""), 
(114,6,"GOOD TRADITIONS","Modernised",""), 
(115,6,"GOOD TRADITIONS","Chapters everywhere",""), 
(116,6,"GOOD TRADITIONS","Secular power",""), 
(117,6,"GOOD TRADITIONS","Flexible tactics",""), 
(118,6,"GOOD TRADITIONS","Open hierarchy",""), 
(119,6,"GOOD TRADITIONS","Integrated in society",""), 
(120,6,"GOOD TRADITIONS","Rich",""), 
(121,6,"GOOD TRADITIONS","Nifty gadgets",""), 
(122,6,"GOOD TRADITIONS","Magical items",""), 
(123,6,"BAD TRADITIONS","Dubious motives",""), 
(124,6,"BAD TRADITIONS","Tradition-bound",""), 
(125,6,"BAD TRADITIONS","Short-sighted",""), 
(126,6,"BAD TRADITIONS","Paranoid and secretive",""), 
(127,6,"BAD TRADITIONS","Closed hierarchy",""), 
(128,6,"BAD TRADITIONS","Factionalised",""), 
(129,6,"BAD TRADITIONS","Strict laws",""), 
(130,6,"BAD TRADITIONS","Mystical oaths",""), 
(131,6,"BAD TRADITIONS","Total obedience",""), 
(132,6,"BAD TRADITIONS","Tyrannical leaders",""), 
(133,6,"BAD TRADITIONS","Obsolete gear",""), 
(134,6,"BAD TRADITIONS","Poor",""), 
#Monstruous
(135,7,"CURSES","Feed","You must subsist on living humans—it might take the form of blood, brains, or spiritual essence but it must be from people. You need to act under pressure to resist feeding whenever a perfect opportunity presents itself"), 
(136,7,"CURSES","Vulnerability","Pick a substance. You suffer +1 harm when you suffer harm from it. If you are bound or surrounded by it, you must act under pressure to use your powers"), 
(137,7,"CURSES","Pure Drive","One emotion rules you. Pick from: hunger, hate, anger, fear, jealousy, greed, joy, pride, envy, lust, or cruelty. Whenever you have a chance to indulge that emotion, you must do so immediately, or act under pressure to resist."), 
(138,7,"CURSES","Dark Master","You have an evil lord who doesn’t know you changed sides. They still give you orders, and they do not tolerate refusal. Or failure"), 
(139,7,"NATURAL ATTACKS","Base: teeth (3-harm intimate)",""), 
(140,7,"NATURAL ATTACKS","Base: claws (2-harm hand)",""), 
(141,7,"NATURAL ATTACKS","Base: magical force (1-harm magical close)",""), 
(142,7,"NATURAL ATTACKS","Base: life-drain (1-harm intimate life-drain",""), 
(143,7,"NATURAL ATTACKS","Extra: Add +1 harm to a base",""), 
(144,7,"NATURAL ATTACKS","Extra: Add ignore-armour to a base",""), 
(145,7,"NATURAL ATTACKS","Extra: Add an extra range to a base (add intimate, hand, or close).",""), 
(146,7,"MOVES","Immortal","You do not age or sicken, and whenever you suffer harm you suffer 1-harm less."), 
(147,7,"MOVES","Unnatural Appeal","Roll +Weird instead of +Charm when you manipulate someone"), 
(148,7,"MOVES","Unholy Strength","Roll +Weird instead of +Tough when you kick some ass."), 
(149,7,"MOVES","Incorporeal","You may move freely through solid objects (but not people)."), 
(150,7,"MOVES","Preternatural Speed","You go much faster than normal people. When you chase, flee, or run take +1 ongoing."), 
(151,7,"MOVES","Claws of the Beast","All your natural attacks get +1 harm"), 
(152,7,"MOVES","Mental Dominion","When you gaze into a normal human’s eyes and exert your will over them, roll +Charm. On a 10+, hold 3. On a 7-9, hold 1. You may spend your hold to give them an order. Regular people will follow your order, whatever it is. Hunters can choose whether they do it or not. If they do, they mark experience"), 
(153,7,"MOVES","Unquenchable Vitality","When you have taken harm, you can heal yourself. Roll +Cool. On a 10+, heal 2-harm and stabilise your injuries. On a 7-9, heal 1-harm and stabilise your injuries. On a miss, your injuries worsen"), 
(154,7,"MOVES","Dark Negotiator","You can use the manipulate someone move on monsters as well as people, if they can reason and talk"), 
(155,7,"MOVES","Flight","You can fly"), 
(156,7,"MOVES","Shapeshifter","You may change your form (usually into an animal). Decide if you have just one alternate form or several, and detail them. You gain +1 to investigate a mystery when using an alternate form’s superior senses (e.g. smell for a wolf, sight for an eagle)."), 
(157,7,"MOVES","Something Borrowed","Take a move from a hunter playbook that is not currently in play"), 
#Mundane
(158,8,"MOVES","Always The Victim","When another hunter uses protect someone to protect you, they mark experience. Whenever a monster captures you, you mark experience"), 
(159,8,"MOVES","Oops!","If you want to stumble across something important, tell the Keeper. You will find something important and useful, although not necessarily related to your immediate problems"), 
(160,8,"MOVES","Let’s Get Out Of Here!","If you can protect someone by telling them what to do, or by leading them out, roll +Charm instead of +Tough"), 
(161,8,"MOVES","Panic Button","When you need to escape, name the route you’ll try and roll +Sharp. On a 10+ you’re out of danger, no problem. On a 7-9 you can go or stay, but if you go it’s going to cost you (you leave something behind or something comes with you). On a miss, you are caught halfway out."), 
(162,8,"MOVES","The Power of Heart","When fighting a monster, if you help someone, don’t roll +Cool. You automatically help as though you’d rolled a 10"), 
(163,8,"MOVES","Trust Me","When you tell a normal person the truth in order to protect them from danger, roll +Charm. On a 10+ they’ll do what you say they should, no questions asked. On a 7-9 they do it, but the Keeper chooses one from: • They ask you a hard question first. • They stall and dither a while. • They have a “better” idea. On a miss, they’re going to think you’re crazy and maybe dangerous too"), 
(164,8,"MOVES","What Could Go Wrong?","Whenever you charge into immediate danger without hedging your bets, hold 2. You may spend your hold to: • Inflict +1 harm. • Reduce someone’s harm suffered by 1. • Take +2 forward on an act under pressure roll"), 
(165,8,"MOVES","Don’t Worry, I’ll Check It Out","Whenever you go off by yourself to check out somewhere (or something) scary, mark experience."), 
#Professional
(166,9,"MOVES","Bottle It Up","If you want, you can take up to +3 bonus when you act under pressure. For each +1 you use, the Keeper holds 1. That hold can be spent later—one for one—to give you -1 on any move except act under pressure"), 
(167,9,"MOVES","Unfazeable","Take +1 Cool (max +3)."), 
(168,9,"MOVES","Battlefield Awareness","You always know what’s happening around you, and what to watch out for. Take +1 armour (max 2-armour) on top of whatever you get from your gear"), 
(169,9,"MOVES","Leave No One Behind","In combat, when you help someone escape, roll +Sharp. On a 10+ you get them out clean. On a 7-9, you can either get them out or suffer no harm, you choose. On a miss, you fail to get them out and you’ve attracted hostile attention"), 
(170,9,"MOVES","Tactical Genius","When you read a bad situation, you may roll +Cool instead of +Sharp"), 
(171,9,"MOVES","Medic","You have a full first aid kit, and the training to heal people. When you do first aid, roll +Cool. On a 10+ the patient is stabilized and healed of 2 harm. On a 7-9 choose one: heal 2 harm or stabilize the injury. On a miss, you cause an extra 1 harm. This move takes the place of regular first aid"), 
(172,9,"MOVES","Mobility",""You have a truck, van, or car built for monster hunting. Choose two good things and one bad thing about it. Good things: roomy; surveillance gear; fast; stealthy; intimidating; classic; medical kit; sleeping space; toolkit; concealed weapons; anonymous; armoured (+1 armour inside); tough; monster cage. Bad things: loud; obvious; temperamental; beaten-up; gas-guzzler; uncomfortable; slow; old.""), 
(173,9,"MOVES","Agency","When you deal with the Agency, requesting help or gear, or making excuses for a failure, roll +Sharp. On a 10+, you’re good—your request for gear or personnel is okayed, or your slip-up goes unnoticed. On a 7-9, things aren’t so great. You might get chewed out by your superiors and there’ll be fallout, but you get what you need for the job. On a miss, you screwed up: you might be suspended or under investigation, or just in the doghouse. You certainly aren’t going to get any help until you sort it all out."), 
(174,9,"RESOURCES","Well-armed",""), 
(175,9,"RESOURCES","Well-financed",""), 
(176,9,"RESOURCES","Rigorous training",""), 
(177,9,"RESOURCES","Official pull",""), 
(178,9,"RESOURCES","Cover identities",""), 
(179,9,"RESOURCES","Offices all over the place",""), 
(180,9,"RESOURCES","Good intel",""), 
(181,9,"RESOURCES","Recognised authority",""), 
(182,9,"RESOURCES","Weird tech gadgets",""), 
(183,9,"RESOURCES","Support teams",""), 
(184,9,"RAD TAPE","Dubious motives",""), 
(185,9,"RAD TAPE","Bureaucratic",""), 
(186,9,"RAD TAPE","Secretive hierarchy",""), 
(187,9,"RAD TAPE","Cryptic missions",""), 
(188,9,"RAD TAPE","Hostile superiors",""), 
(189,9,"RAD TAPE","Inter-departmental rivalry",""), 
(190,9,"RAD TAPE","Budget cuts",""), 
(191,9,"RAD TAPE","Take no prisoners policy",""), 
(192,9,"RAD TAPE","Live capture policy",""),
#Spell-Slinger
(193,10,"COMBAT MAGIC","Blast","2-harm magic close obvious loud"), 
(194,10,"COMBAT MAGIC","Ball","1-harm magic area close obvious loud"), 
(195,10,"COMBAT MAGIC","Missile","1-harm magic far obvious loud"), 
(196,10,"COMBAT MAGIC","Wall","1-harm magic barrier close 1-armour obvious loud"), 
(197,10,"EFFECTS","Fire","Add “+2 harm fire” to a base. If you get a 10+ on a combat magic roll, the fire won’t spread"), 
(198,10,"EFFECTS","Force or Wind","Add “+1 harm forceful” to a base, or “+1 armour” to a wall."), 
(199,10,"EFFECTS","Lightning or Entropy","Add “+1 harm messy” to a base"), 
(200,10,"EFFECTS","Frost or Ice","Adds “-1 harm +2 armour” to a wall, or “+1 harm restraining” to other bases"), 
(201,10,"EFFECTS","Earth","Add “forceful restraining” to a base."), 
(202,10,"EFFECTS","Necromantic","Add “life-drain” to a base"), 
(203,10,"MOVES","Tools and Techniques","To use your combat magic effectively, you rely on a collection of tools and techniques. Cross off one; you’ll need the rest. • Consumables: You need certain supplies— powders, oils, etc—on hand, some will be used up each cast. If you don’t have them, take 1-harm ignore-armour when you cast. • Foci: You need wands, staves, and other obvious props to focus. If you don’t have what you need, your combat magic does 1 less harm. • Gestures: You need to wave your hands around to use combat magic. If you’re restrained, take -1 ongoing for combat magic. • Incantations: You must speak in an arcane language to control your magic. If you use combat magic without speaking, act under pressure to avoid scrambling your thoughts."), 
(204,10,"MOVES","Advanced Arcane Training","If you have two of your three Tools and Techniques at the ready, you may ignore the third one."), 
(205,10,"MOVES","Arcane Reputation","Pick three big organizations or groups in the supernatural community, which can include some of the more sociable types of monsters. They’ve heard of you and respect your power. With affected humans, take +1 forward when you manipulate them. You may manipulate affected monsters as if they were human, with no bonus"), 
(206,10,"MOVES","Could’ve Been Worse","When you miss a use magic roll you can choose one of the following options instead of losing control of the magic: • Fizzle: The preparations and materials for the spell are ruined. You’ll have to start over from scratch with the prep time doubled. • This Is Gonna Suck: The effect happens, but you trigger all of the listed glitches but one. You pick the one you avoid."), 
(207,10,"MOVES","Enchanted Clothing","Pick an article of every-day clothing–it’s enchanted without any change in appearance. Take -1 harm from any source that tries to get at you through the garment."), 
(208,10,"MOVES","Forensic Divination","When you successfully investigate a mystery, you may ask “What magic was done here?” as a free extra question"), 
(209,10,"MOVES","Go Big or Go Home","When you must use magic as a requirement for Big Magic, take +1 ongoing to those use magic rolls"), 
(210,10,"MOVES","Not My Fault","+1 to act under pressure when you are dealing with the consequences of your own spellcasting"), 
(211,10,"MOVES","Practitioner","Choose two effects available to you under use magic. Take +1 to use magic whenever you choose one of those effects."), 
(212,10,"MOVES","Shield Spell","When you protect someone, gain 2-armour against any harm that is transferred to you. This doesn’t stack with your other armour, if any"), 
(213,10,"MOVES","Third Eye","When you read a bad situation, you can open up your third eye for a moment to take in extra information. Take +1 hold on any result of 7 or more, plus you can see invisible things. On a miss, you may still get 1 hold, but you’re exposed to supernatural danger. Unfiltered hidden reality is rough on the mind!"), 
#Spooky
(214,11,"MOVES","Telepathy","You can read people’s thoughts and put words in their mind. This can allow you to investigate a mystery or read a bad situation without needing to actually talk. You can also manipulate someone without speaking. You still roll moves as normal, except people will not expect the weirdness of your mental communication"), 
(215,11,"MOVES","Hex","When you cast a spell (with use magic), as well as the normal effects, you may pick from the following: • The target contracts a disease. • The target immediately suffers harm (2-harm magic ignore-armour). • The target breaks something precious or important"), 
(216,11,"MOVES","The Sight","You can see the invisible, especially spirits and magical influences. You may communicate with (maybe even make deals with) the spirits you see, and they give you more opportunities to spot clues when you investigate a mystery"), 
(217,11,"MOVES","Premonitions","At the start of each mystery, roll +Weird. On a 10+, you get a detailed vision of something bad that is yet to happen. You take +1 forward to prevent it coming true, and mark experience if you stop it. On a 7-9+ you get clouded images of something bad that is yet to happen: mark experience if you stop it. On a miss, you get a vision of something bad happening to you and the Keeper holds 3, to be spent one-for-one as penalties to rolls you make"), 
(218,11,"MOVES","Hunches","When something bad is happening (or just about to happen) somewhere that you aren’t, roll +Sharp. On a 10+ you knew where you needed to go, just in time to get there. On a 7-9, you get there late—in time to intervene, but not prevent it altogether. On a miss, you get there just in time to be in trouble yourself."), 
(219,11,"MOVES","Tune In","ou can attune your mind to a monster or minion. Roll +Weird. On a 10+, hold 3. On a 7-9, hold 1. On a miss, the monster becomes aware of you. Spend one hold to ask the Keeper one of the following questions, and gain +1 ongoing while acting on the answers: • Where is the creature right now? • What is it planning to do right now? • Who is it going to attack next? • Who does it regard as the biggest threat? • How can I attract its attention?"), 
(220,11,"MOVES","The Big Whammy","You can use your powers to kick some ass: roll +Weird instead of +Tough. The attack has 2-harm close obvious ignore-armour. On a miss, you’ll get a magical backlash."), 
(221,11,"MOVES","Jinx","You can encourage coincidences to occur, the way you want. When you jinx a target, roll +Weird. On a 10+ hold 2 and on a 7-9 hold 1. On a miss, the Keeper holds 2 over you to be used in the same way. Spend your hold to: • Interfere with a hunter, giving them -1 forward. • Help a hunter, giving them +1 forward, by interfering with their enemy. • Interfere with what a monster, minion, or bystander is trying to do. • Inflict 1-harm on the target due to an accident. • The target finds something you left for them. • The target loses something that you will soon find."), 
(222,11,"DARK SIDE","Violence",""), 
(223,11,"DARK SIDE","Depression",""), 
(224,11,"DARK SIDE","Secrets",""), 
(225,11,"DARK SIDE","Lust",""), 
(226,11,"DARK SIDE","Dark bargain",""), 
(227,11,"DARK SIDE","Guilt",""), 
(228,11,"DARK SIDE","Soulless",""), 
(229,11,"DARK SIDE","Addiction",""), 
(230,11,"DARK SIDE","Mood swings",""), 
(231,11,"DARK SIDE","Rage",""), 
(232,11,"DARK SIDE","Self-destruction",""), 
(233,11,"DARK SIDE","Greed for power",""), 
(234,11,"DARK SIDE","Poor impulse control",""), 
(235,11,"DARK SIDE","Hallucinations",""), 
(236,11,"DARK SIDE","Pain",""), 
(237,11,"DARK SIDE","Paranoia",""), 
#Wronged
(238,12,"MOVES","I Know My Prey","You get +1 ongoing when knowingly investigating, pursuing or fighting the breed of monster that caused your loss"), 
(239,12,"MOVES","Berserk","No matter how much harm you take, you can always keep going until the current fight is over. During a fight, the Keeper may not use harm moves on you and you cannot die. When the fight ends, all harm takes effect as normal"), 
(240,12,"MOVES","NEVER AGAIN","In combat, you may choose to protect someone without rolling, as if you had rolled a 10+, but you may not choose to “suffer little harm.”"), 
(241,12,"MOVES","What Does Not Kill Me...:","If you have suffered harm in a fight, you gain +1 ongoing until the fight is over"), 
(242,12,"MOVES","Fervor","When you manipulate someone, roll +Tough instead of +Charm."), 
(243,12,"MOVES","Safety First","You have jury-rigged extra protection into your gear, giving you +1 armour (maximum 2-armour)."), 
(244,12,"MOVES","DIY Surgery","When you do quick and dirty first aid on someone (including yourself), roll +Cool. On a 10+ it’s all good, it counts as normal first aid, plus stabilize the injury and heal 1 harm. On a 7-9 it counts as normal first aid, plus one of these, your choice: • Stabilise the injury but the patient takes -1 forward. • Heal 1-harm and stabilise for now, but it will return as 2-harm and become unstable again later. • Heal 1-harm and stabilise but the patient takes -1 ongoing until it’s fixed properly."), 
(245,12,"MOVES","Tools Matter","With your signature weapon (see your gear, below), you get +1 to kick some ass"), 
(246,12,"WHO YOU LOST","Your parent(s)",""), 
(247,12,"WHO YOU LOST","Your sibling(s)",""), 
(248,12,"WHO YOU LOST","Your spouse/partner",""), 
(249,12,"WHO YOU LOST","Your child(ren)",""), 
(250,12,"WHO YOU LOST","Your best friend(s)",""), 
(251,12,"WHAT DID IT?","My prey",""), 
(252,12,"WHY COULDN'T YOU SAVE THEM?","at fault",""), 
(253,12,"WHY COULDN'T YOU SAVE THEM?","selfish",""), 
(254,12,"WHY COULDN'T YOU SAVE THEM?","injured",""), 
(255,12,"WHY COULDN'T YOU SAVE THEM?","weak",""), 
(256,12,"WHY COULDN'T YOU SAVE THEM?","slow",""), 
(257,12,"WHY COULDN'T YOU SAVE THEM?","scared",""), 
(258,12,"WHY COULDN'T YOU SAVE THEM?","in denia",""), 
(259,12,"WHY COULDN'T YOU SAVE THEM?","complicit","");


CREATE TABLE GEAR(
	ID INTEGER PRIMARY KEY,
    GEAR_NAME VARCHAR(150),
    TAGS TEXT
);
INSERT INTO GEAR VALUES
#Chosen
(1, "Staff", "1-harm;hand/close"),
(2, "Haft", "2-harm;hand;heavy"),
(3, "Handle", "1-harm;hand;balanced"),
(4, "Chain", "1-harm;hand;area"),
(5, "Artifact", "magic"),
(6, "Spikes", "+1 harm;messy"),
(7, "Blade", "+1 harm"),
(8, "Heavy", "+1 harm"),
(9, "Long", "Close"),
(10, "Throwable", "Close"),
(11, "Chain", "area"),
#Crooked
(12, ".22 revolver", "1-harm;close;reload;small"),
(13, ".38 revolver", "2-harm;close;reload;loud"),
(14, "9mm", "2-harm;close;loud"),
(15, "Shotgun", "3-harm;close;messy"),
(16, "Hunting rifle", "2-harm;far;loud"),
(17, "Big Knife", "1-harm;hand"),
(18, "Baseball bat", "1-harm;hand"),
(19, "Submachinegun", "2-harm;close;reload;auto"),
(20, "Assault rifle", "3-harm;close/far;auto"),
#Divine
(21, "Flamming sword", "3-harm;hand;fire;holy"),
(22, "Thunder hammer", "3-harm;hand;stun;holy"),
(23, "Razor whip", "3-harm;area;messy;holy"),
(24, "Five demon bag", "3-harm;close;magic;holy"),
(25, "Silver trident", "3-harm;hand;silver;holy"),
#Expert
(26, "Mallet & wooden stakes", "3-harm;intimate;slow;wooden"),
(27, "Silver sword", "2-harm;hand;messy;silver"),
(28, "Cold iron sword", "2-harm;hand;messy;iron"),
(29, "Blessed knife", "2-harm;hand;holy"),
(30, "Magical dagger", "2-harm;hand;magic"),
(31, "Juju bag", "1-harm;far;magic"),
(32, "Flamethrower", "3-harm;close;reload;heavy;volatile"),
(33, "Magnum", "3-harm;close;reload;loud"),
(34, "Shotgun", "3-harm;close;messy;loud"),
#Flake
(35, "Throwing knifes", "1-harm;close;many"),
(36, "Holdout pistol", "2-harm;close;loud;reload"),
(37, "Garrote", "3-harm;intimate"),
(38, "Watchman´s flashlight", "1-harm;hand"),
(39, "Weighted gloves/brassknuckles", "1-harm;hand"),
(40, "Butterfly knife/folding knife", "1´harm;hand"),
#Initiate
(41, "Sword", "2-harm;hand;messy"),
(42, "Axe", "2-harm;hand;messy"),
(43, "Big sword", "3-harm;hand;messy;heavy"),
(44, "Big axe", "3-harm;hand;messy;slow;heavy"),
(45, "Silver knife", "1-harm;hand;silver"),
(46, "Fighting sticks", "1-harm;hand;quick"),
(47, "Spear", "2-harm;hand/close"),
(48, "Mace", "2-harm;hand;messy"),
(49, "Crossbow", "2-harm;close;slow"),
(50, "Sniper rifle", "3-harm;far"),
#Monstruous
(51, "Brass knuckles", "1-harm;hand;quiet;small"),
(52, "Huge sword", "3-harm;hand;heavy"),
#Mundane
(53, "Golf club, baseball bat, cricket bat or Hockey stick", "2-harm;hand;innocuous;messy"),
(54, "Pocket knife or multitool", "1-harm;hand;usefull;small"),
(55, "Small handgun", "2-harm;close;loud;reload"),
(56, "Hunting rifle", "3-harm;far;loud;reload"),
(57, "Sledge-hammer or fire axe", "3-harm;hand;messy"),
(58, "Nunchucks", "2-harm;hand;area"),
(59, "Skateboard", null),
(60, "Bicycle", null),
(61, "Fairly new car in decent conditions", null),
(62, "Classic car in terrible conditions", null),
(63, "Motorcycle", null),
(64, "Van", null),
#Professional
(65, "Assault rifle", "3-harm;far;area;loud;reload"),
(66, "Grenade launcher", "4-harm;far;area;messy;loud;reload"),
(67, "Sniper rifle", "4-harm;far"),
(68, "Grenades", "4-harm;close;area;messy;loud"),
(69, "Submachine gun", "3-harm;close;area;loud;reload"),
#Spell-Slinger
(70, "Old revolver", "2-harm;close;reload;loud"),
(71, "Ritual knife", "1-harm;hand"),
(72, "Heirloom sword", "2-harm;hand;messy"),
#Spooky
/*
Same as crooked
*/
#Wronged
(73, "Sawn-off shotgun", "3-harm;close;loud"),
(74, "Hand cannon", "3-harm;close;loud"),
(75, "Fighting knife", "2-harm;hand;quiet"),
(76, "Huge sword or huge axe", "3-harm;hand;messy;heavy"),
(77, "Specialist weapons for destroying your foes", "4-harm"),
(78, "Enchanted dagger", "2-harm;hand;magic"),
(79, "Chainsaw", "3-harm;hand;messy;unreliable;loud;heavy"),
(80, "Brass knuckles", "1-harm;hand,stealthy"),
(81, "Assault rifle", "3-harm;close;area;loud;reload");
CREATE TABLE GEAR_PLAYBOOKS(
	PLB_ID INTEGER,
    GR_ID INTEGER,    
    PRIMARY KEY (PLB_ID, GR_ID),
    CONSTRAINT FK_GP_PLB FOREIGN KEY (PLB_ID) REFERENCES PLAYBOOKS (ID),
    CONSTRAINT FK_GP_GR FOREIGN KEY (GR_ID) REFERENCES GEAR (ID)
);
INSERT INTO GEAR_PLAYBOOKS VALUES
(1, 1),
(1, 2),
(1, 3),
(1, 4),
(1, 5),
(1, 6),
(1, 7),
(1, 8),
(1, 9),
(1, 10),
(1, 11),
(2, 12),
(2, 13),
(2, 14),
(2, 15),
(2, 16),
(2, 17),
(2, 18),
(2, 19),
(2, 20),
(3, 21),
(3, 22),
(3, 23),
(3, 24),
(3, 25),
(4, 26),
(4, 27),
(4, 28),
(4, 29),
(4, 30),
(4, 31),
(4, 32),
(4, 33),
(4, 34),
(5, 13),
(5, 14),
(5, 16),
(5, 33),
(5, 34),
(5, 17),
(5, 35),
(5, 36),
(5, 37),
(5, 38),
(5, 39),
(5, 40),
(6, 41),
(6, 42),
(6, 43),
(6, 44),
(6, 45),
(6, 46),
(6, 47),
(6, 48),
(6, 49),
(6, 13),
(6, 14),
(6, 50),
(6, 33),
(6, 15),
(7, 13),
(7, 14),
(7, 33),
(7, 15),
(7, 17),
(7, 51),
(7, 41),
(7, 52),
(8, 53),
(8, 54),
(8, 55),
(8, 56),
(8, 57),
(8, 58),
(8, 59),
(8, 60),
(8, 61),
(8, 62),
(8, 63),
(8, 64),
(9, 65),
(9, 66),
(9, 67),
(9, 68),
(9, 69),
(9, 13),
(9, 14),
(9, 16),
(9, 34),
(9, 17),
(10, 70),
(10, 71),
(10, 72),
(11, 13),
(11, 14),
(11, 16),
(11, 15),
(11, 17),
(12, 73),
(12, 74),
(12, 75),
(12, 76),
(12, 77),
(12, 78),
(12, 79),
(12, 13),
(12, 14),
(12, 16),
(12, 34),
(12, 17),
(12, 80),
(12, 81);
CREATE VIEW GEAR_PLAYBOOKS_FULLINFO_VIEW
AS
select PLB.ID AS 'PLAYBOOK_ID', 
		PLB.TITLE AS 'PLAYBOOK_TITLE',
        GR.ID  AS 'GEAR_ID',
        GR.GEAR_NAME AS 'GEAR_NAME', 
        GR.TAGS AS  'GEAR_TAGS'
from
PLAYBOOKS PLB inner join gear_playbooks GP
	ON PLB.ID = GP.plb_id
inner join GEAR GR
	ON GP.gr_id = GR.id;
CREATE TABLE IMPROVEMENTS(
	ID INTEGER PRIMARY KEY,
    IMP_NAME VARCHAR(150),
    ADVANCED BOOLEAN
);
INSERT INTO IMPROVEMENTS VALUES
(1,"Get +1 Charm max +3",0),
(2,"Get +1 Cool max +3",0),
(3,"Get +1 Sharp max +3",0),
(4,"Get +1 Tought max +3",0),
(5,"Get +1 Weird max +3",0),
(6,"Take a move from another playbook",0),
(7,"Take a move from another playbook",0),
(8,"Get +1 to any rating, max +3",1),
(9,"Change this hunter to a new type",1),
(10,"Create a second hunter to play as this one",1),
(11,"Mark two of the basic moved as advanced",1),
(12,"Mark another two of the basic moves as advanced",1),
(13,"Retire this hunter to safety",1),
(14,"Take another Chosen move",0),
(15,"Take another Chosen move",0),
(16,"Take another Crooked move",0),
(17,"Take another Crooked move",0),
(18,"Take another Divine move",0),
(19,"Take another Divine move",0),
(20,"Take another Expert move",0),
(21,"Take another Expert move",0),
(22,"Take another Flake move",0),
(23,"Take another Flake move",0),
(24,"Take another Initiate move",0),
(25,"Take another Initiate move",0),
(26,"Take another Monstruous move",0),
(27,"Take another Monstruous move",0),
(28,"Take another Mundane move",0),
(29,"Take another Mundane move",0),
(30,"Take another Professional move",0),
(31,"Take another Professional move",0),
(32,"Take another Spell-Slinger move",0),
(33,"Take another Spell-Slinger move",0),
(34,"Take another Spooky move",0),
(35,"Take another Spooky move",0),
(36,"Take another Wronged move",0),
(37,"Take another Wronged move",0),
(38,"Gain an ally",0),
(39,"Gain an ally: one of your old crew",0),
(40,"Recover a stash of money from the old days, enough to live without care... for a year or two",0),
(41,"Gain a lesser divine being as an ally, sent from above to help with your mission",0),
(42,"Add an option to your haven",0),
(43,"Add an option to your haven",0),
(44,"Get a haven, like the Expert has, with two options",0),
(45,"Gain another option for your haven",0),
(46,"Get command of your chapter of the Sect",0),
(47,"Get a Sect team under your command",0),
(48,"Gain a haven, like the Expert has, with two options",0),
(49,"Take a natural attacks pick",0),
(50,"Get back one used Luck point",0),
(51,"Get back one used Luck point",0),
(52,"Add a new resource tag for your Agency or change a red tape tag",0),
(53,"Get command of an Agency team of monster hunters",0),
(54,"Take another Combat Magic pick",0),
(55,"Change some, or all, your dark side tags",0),
(56,"Get a mystical library, like the Expert’s haven option",0),
(57,"Gain a haven, like the Expert has, with two options",0),
(58,"Add one more option to your haven",0),
(59,"Delete one of your Doom tags, and (optionally) one of your Heroic tags. You have changed that aspect of your destiny",1),
(60,"Erase one used luck mark from your playbook",1),
(61,"Change your mission. Select a different mission from the normal options, or (with the Keeper’s agreement) a new mission of your creation",1),
(62,"Become the leader, or effective leader, of the whole Sect",1),
(63,"Free yourself from the curse of your kind. Your curse no longer applies, but you lose 1 Weird",1),
(64,"You turn evil (again). Retire this character, they become one of the Keeper’s threats",1),
(65,"Get some or all of the other players’ hunters hired by your agency. They get the deal with the agency move, as well as salary and benefits",1),
(66,"Take another Combat Magic pick",1),
(67,"You may cross off another option from your Tools and Techniques",1),
(68,"You discover how to use your powers at a lower price. Delete one dark side tag permanently",1),
(69,"You track down the specific monster(s) responsible for your loss. The Keeper must make the next mystery about them",1),
(70,"Change the target of your vengeful rage. Pick a new monster breed: I know my prey now applies to them instead",1);
CREATE TABLE IMPROVEMENTS_PLAYBOOKS(
	PLB_ID INTEGER,
	IMP_ID INTEGER,    
    CONSTRAINT FK_IP_PLB FOREIGN KEY (PLB_ID) REFERENCES PLAYBOOKS (ID),
    CONSTRAINT FK_IP_IMP FOREIGN KEY (IMP_ID) REFERENCES IMPROVEMENTS (ID)
);
INSERT INTO IMPROVEMENTS_PLAYBOOKS VALUES
(1, 1),
(1, 2),
(1, 3),
(1, 4),
(1, 5),
(1, 6),
(1, 7),
(1, 14),
(1, 15),
(1, 38),
(1, 8),
(1, 9),
(1, 10),
(1, 11),
(1, 12),
(1, 13),
(1, 59),
(2, 1),
(2, 2),
(2, 3),
(2, 4),
(2, 16),
(2, 17),
(2, 39),
(2, 40),
(2, 6),
(2, 7),
(2, 8),
(2, 9),
(2, 10),
(2, 11),
(2, 12),
(2, 13),
(2, 60),
(3, 1),
(3, 2),
(3, 3),
(3, 4),
(3, 5),
(3, 18),
(3, 19),
(3, 41),
(3, 6),
(3, 7),
(3, 8),
(3, 9),
(3, 10),
(3, 11),
(3, 12),
(3, 13),
(3, 60),
(3, 61),
(4, 1),
(4, 2),
(4, 3),
(4, 5),
(4, 20),
(4, 21),
(4, 42),
(4, 43),
(4, 6),
(4, 7),
(4, 8),
(4, 9),
(4, 10),
(4, 11),
(4, 12),
(4, 13),
(5, 1),
(5, 2),
(5, 3),
(5, 5),
(5, 22),
(5, 23),
(5, 44),
(5, 45),
(5, 6),
(5, 7),
(5, 8),
(5, 9),
(5, 10),
(5, 11),
(5, 12),
(5, 13),
(6, 2),
(6, 3),
(6, 4),
(6, 5),
(6, 24),
(6, 25),
(6, 46),
(6, 47),
(6, 6),
(6, 7),
(6, 8),
(6, 9),
(6, 10),
(6, 11),
(6, 12),
(6, 13),
(6, 62),
(7, 1),
(7, 2),
(7, 3),
(7, 4),
(7, 26),
(7, 27),
(7, 48),
(7, 49),
(7, 6),
(7, 7),
(7, 8),
(7, 9),
(7, 10),
(7, 11),
(7, 12),
(7, 13),
(7, 63),
(7, 64),
(8, 1),
(8, 2),
(8, 3),
(8, 4),
(8, 28),
(8, 29),
(8, 50),
(8, 51),
(8, 6),
(8, 7),
(8, 8),
(8, 9),
(8, 10),
(8, 11),
(8, 12),
(8, 13),
(8, 50),
(8, 51),
(9, 1),
(9, 2),
(9, 3),
(9, 4),
(9, 30),
(9, 31),
(9, 52),
(9, 53),
(9, 6),
(9, 7),
(9, 8),
(9, 9),
(9, 10),
(9, 11),
(9, 12),
(9, 13),
(9, 65),
(10, 2),
(10, 3),
(10, 4),
(10, 5),
(10, 32),
(10, 33),
(10, 6),
(10, 7),
(10, 54),
(10, 8),
(10, 9),
(10, 10),
(10, 11),
(10, 12),
(10, 13),
(10, 60),
(10, 66),
(10, 67),
(11, 1),
(11, 2),
(11, 3),
(11, 5),
(11, 34),
(11, 35),
(11, 55),
(11, 56),
(11, 6),
(11, 7),
(11, 8),
(11, 9),
(11, 10),
(11, 11),
(11, 12),
(11, 13),
(11, 68),
(12, 2),
(12, 3),
(12, 4),
(12, 5),
(12, 36),
(12, 37),
(12, 48),
(12, 58),
(12, 6),
(12, 7),
(12, 8),
(12, 9),
(12, 10),
(12, 11),
(12, 12),
(12, 13),
(12, 69),
(12, 70);
CREATE TABLE BACKGROUND(
	ID INTEGER PRIMARY KEY,
    BACK_DESCRIPTION TEXT,
    PLB_ID INTEGER,
    CONSTRAINT FK_BCK_PLB FOREIGN KEY (PLB_ID) REFERENCES PLAYBOOKS (ID)
		ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE HUNTER(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FULLNAME VARCHAR(50),
    PLB_ID INTEGER,
    PLY_ID INTEGER,
    LOOK TEXT,
    CHARM INTEGER,
    COOL INTEGER,
    TOUGHT INTEGER,
    WEIRD INTEGER,
    LUCK INTEGER,
    HARM INTEGER,
    EXP INTEGER,
    LORE TEXT,
    CONSTRAINT FK_HU_PLB  FOREIGN KEY (PLB_ID) REFERENCES PLAYBOOKS (ID)
		ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_HU_PLY  FOREIGN KEY (PLY_ID) REFERENCES PLAYER (ID)
		ON DELETE CASCADE ON UPDATE CASCADE
); 
